import type { Metadata } from "next";
import "../globals.css";
import Navbar from "@/components/Navbar";

export const metadata: Metadata = {
  title: "Mitchell's Awesome Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="max-w-7xl mx-auto py-8">
        <Navbar />
        <main className="w-full h-full flex flex-col items-center p-2 md:p-0">
          {children}
        </main>
      </body>
    </html>
  );
}
